import Footer from './Footer'
import Header from './components/header/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { getFilm } from './hooks/getdData'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
   //  await DeleteAllFilms()
   const data = await getFilm()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
